//This lets other files acsess the currently running objects variables (much better then manually doing this in the compiler each time :3)
#include "../gml/structs.h"
#include "customfuncs.h"
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include "../gm_funcs/drawing.h"
#include "../gm_funcs/input.h"
#include "../gm_funcs/input.h"
#include "../helpers/asset_toid.h"
#include "../gm_funcs/misc.h"
#include "../gm_funcs/collision.h"
#include "../gm_funcs/audio.h"
#include "../gm_funcs/filesystem.h"
#include "../custom_funcs/customfuncs.h"
#include "../variable_handler.h"
#include <variant>
#include "../helpers/other.h"

#define x GetVar(varId_x, *self)
#define y GetVar(varId_y, *self)
#define sprite_index GetVar(varId_sprite_index, *self)
#define image_xscale GetVar(varId_image_xscale, *self)
#define image_yscale GetVar(varId_image_yscale, *self)
#define sprite_xoffset GetVar(varId_sprite_xoffset, *self)
#define sprite_yoffset GetVar(varId_sprite_yoffset, *self)
#define image_index GetVar(varId_image_index, *self)
#define alarm GetVar(varId_alarm, *self)
#define id GetVar(varId_id, *self)
#define visible GetVar(varId_visible, *self)
#define solid GetVar(varId_solid, *self)
#define persistent GetVar(varId_persistent, *self)
#define depth GetVar(varId_depth, *self)
#define layer GetVar(varId_layer, *self)
#define on_ui_layer GetVar(varId_on_ui_layer, *self)
#define collision_space GetVar(varId_collision_space, *self)
#define direction GetVar(varId_direction, *self)
#define friction GetVar(varId_friction, *self)
#define gravity GetVar(varId_gravity, *self)
#define gravity_direction GetVar(varId_gravity_direction, *self)
#define hspeed GetVar(varId_hspeed, *self)
#define vspeed GetVar(varId_vspeed, *self)
#define speed GetVar(varId_speed, *self)
#define xstart GetVar(varId_xstart, *self)
#define ystart GetVar(varId_ystart, *self)
#define xprevious GetVar(varId_xprevious, *self)
#define yprevious GetVar(varId_yprevious, *self)
#define object_index GetVar(varId_object_index, *self)
#define sprite_width GetVar(varId_sprite_width, *self)
#define sprite_height GetVar(varId_sprite_height, *self)
#define image_alpha GetVar(varId_image_alpha, *self)
#define image_angle GetVar(varId_image_angle, *self)
#define image_blend GetVar(varId_image_blend, *self)
#define image_number GetVar(varId_image_number, *self)
#define image_speed GetVar(varId_image_speed, *self)
#define finalCamX GetVar(varId_finalCamX, *self)
#define finalCamY GetVar(varId_finalCamY, *self)
#define camTrailSpd GetVar(varId_camTrailSpd, *self)
#define view_w GetVar(varId_view_w, *self)
#define view_h GetVar(varId_view_h, *self)
#define view_enabled GetVar(varId_view_enabled, *self)
#define _camX GetVar(varId__camX, *self)
#define _camY GetVar(varId__camY, *self)
#define finalCamX GetVar(varId_finalCamX, *self)
#define finalCamY GetVar(varId_finalCamY, *self)
#define camTrailSpd GetVar(varId_camTrailSpd, *self)
#define view_w GetVar(varId_view_w, *self)
#define view_h GetVar(varId_view_h, *self)
#define view_enabled GetVar(varId_view_enabled, *self)
#define _camX GetVar(varId__camX, *self)
#define _camY GetVar(varId__camY, *self)
#define os_version GetVar(varId_os_version, *self)
#define finalCamX GetVar(varId_finalCamX, *self)
#define finalCamY GetVar(varId_finalCamY, *self)
#define camTrailSpd GetVar(varId_camTrailSpd, *self)
#define view_w GetVar(varId_view_w, *self)
#define view_h GetVar(varId_view_h, *self)
#define view_enabled GetVar(varId_view_enabled, *self)
#define _camX GetVar(varId__camX, *self)
#define _camY GetVar(varId__camY, *self)
#define os_version GetVar(varId_os_version, *self)
#define hsp GetVar(varId_hsp, *self)
#define vsp GetVar(varId_vsp, *self)
#define spd GetVar(varId_spd, *self)
#define mask_index GetVar(varId_mask_index, *self)
#define key_left GetVar(varId_key_left, *self)
#define key_right GetVar(varId_key_right, *self)
#define key_up GetVar(varId_key_up, *self)
#define key_down GetVar(varId_key_down, *self)
#define finalCamX GetVar(varId_finalCamX, *self)
#define finalCamY GetVar(varId_finalCamY, *self)
#define camTrailSpd GetVar(varId_camTrailSpd, *self)
#define view_w GetVar(varId_view_w, *self)
#define view_h GetVar(varId_view_h, *self)
#define view_enabled GetVar(varId_view_enabled, *self)
#define _camX GetVar(varId__camX, *self)
#define _camY GetVar(varId__camY, *self)
#define os_version GetVar(varId_os_version, *self)
#define hsp GetVar(varId_hsp, *self)
#define vsp GetVar(varId_vsp, *self)
#define spd GetVar(varId_spd, *self)
#define mask_index GetVar(varId_mask_index, *self)
#define key_run GetVar(varId_key_run, *self)
#define key_run_2 GetVar(varId_key_run_2, *self)
#define key_run_3 GetVar(varId_key_run_3, *self)
#define key_jump GetVar(varId_key_jump, *self)
#define key_jump_2 GetVar(varId_key_jump_2, *self)
#define key_jump_3 GetVar(varId_key_jump_3, *self)
#define key_crouch GetVar(varId_key_crouch, *self)
#define key_crouch_2 GetVar(varId_key_crouch_2, *self)
#define key_crouch_3 GetVar(varId_key_crouch_3, *self)
#define key_Start GetVar(varId_key_Start, *self)
#define debugCR GetVar(varId_debugCR, *self)
#define jumpKeyBuffered GetVar(varId_jumpKeyBuffered, *self)
#define jumpKeyBufferTimer GetVar(varId_jumpKeyBufferTimer, *self)
#define bufferTime GetVar(varId_bufferTime, *self)
#define xDir GetVar(varId_xDir, *self)
#define yDir GetVar(varId_yDir, *self)
#define scSpeed GetVar(varId_scSpeed, *self)
#define i GetVar(varId_i, *self)
